networks:
  orchestrator:
  db:
services:
  orchestrator:
    build:
      dockerfile: "./docker/dev/Dockerfile.orchestrator"
      context: "."
      target: "orchestrator"
    command: "/out/app/orchestrator"
    deploy:
      restart_policy:
        delay: 5s
        window: 60s
    ports:
      - "127.0.0.1:1323:1323"
    networks:
      - "orchestrator"
      - "db"
    secrets:
      - "db_password"
      - "jwt_secret"
    depends_on:
      - "db"
    develop:
      watch:
        - action: "rebuild"
          path: "./backend/"
  agent:
    build:
      dockerfile: "./docker/dev/Dockerfile.agent"
      context: "."
      target: "agent"
    command: "/out/app/agent"
    networks:
      - "orchestrator"
    depends_on:
      - "orchestrator"
    deploy:
      restart_policy:
        delay: 5s
        window: 60s
      replicas: 4
    develop:
      watch:
        - action: "rebuild"
          path: "./backend/"
  db:
    image: "postgres:16.1"
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
    ports:
      - "127.0.0.1:2069:5432"
    secrets:
      - "db_password"
    networks:
      - "db"
  frontend:
    build:
      dockerfile: "./docker/dev/Dockerfile.frontend"
      context: "."
    command: "pnpm run dev --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    deploy:
      restart_policy:
        delay: 5s
        window: 60s
    develop:
      watch:
        - action: "rebuild"
          path: "./frontend/pnpm-lock.yaml"
        - action: "sync"
          path: "./frontend/"
          target: /app
secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret
